basePath: /
consumes:
- application/json
definitions:
  Loadout:
    description: Loadout represents a Warzone loadout, complete with a primary weapon,
      secondary weapon, three perks, and lethal and tactical equipment
    properties:
      lethal:
        type: string
        x-go-name: Lethal
      meta_loadout:
        type: boolean
        x-go-name: Meta
      perk_one:
        type: string
        x-go-name: PerkOne
      perk_three:
        type: string
        x-go-name: PerkThree
      perk_two:
        type: string
        x-go-name: PerkTwo
      primary:
        $ref: '#/definitions/Weapon'
      secondary:
        $ref: '#/definitions/Weapon'
      tactical:
        type: string
        x-go-name: Tactical
    type: object
    x-go-package: github.com/chancetudor/dubzone-api/internal/models
  Weapon:
    properties:
      ammo:
        type: string
        x-go-name: Ammo
      barrel:
        type: string
        x-go-name: Barrel
      category:
        type: string
        x-go-name: Category
      laser:
        type: string
        x-go-name: Laser
      meta_weapon:
        type: boolean
        x-go-name: Meta
      muzzle:
        type: string
        x-go-name: Muzzle
      optic:
        type: string
        x-go-name: Optic
      perk:
        type: string
        x-go-name: Perk
      rear_grip:
        type: string
        x-go-name: RearGrip
      stock:
        type: string
        x-go-name: Stock
      under_barrel:
        type: string
        x-go-name: Underbarrel
      weapon_name:
        type: string
        x-go-name: WeaponName
    title: Weapon represents a Warzone weapon, complete with a category and all recommended
      attachments.
    type: object
    x-go-package: github.com/chancetudor/dubzone-api/internal/models
host: localhost
info:
  contact:
    email: hi@cmtudor.me
    name: Chance Tudor
    url: https://cmtudor.me
  description: A service that communicates meta weapons and loadouts, stored in a
    database, to a consumer in JSON format.
  title: Dubzone API.
  version: 0.0.2
paths:
  /loadouts:
    get:
      operationId: listLoadouts
      responses:
        "200":
          $ref: '#/responses/loadoutsResponse'
      summary: Returns a list of all loadouts.
      tags:
      - loadouts
produces:
- application/json
responses:
  loadoutsResponse:
    description: A list of loadouts returned in a successful response.
    schema:
      items:
        $ref: '#/definitions/Loadout'
      type: array
schemes:
- https
swagger: "2.0"
